<?php
/**
 * Страница "Форма добавления / редактирования метки".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения RosGear.
 * 
 * @copyright Copyright (c) 2015 RosGear
 * @license https://rosgear.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования термина</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/form.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов <a href="<?= $url('grid') ?>">списка</a> или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название.</b> Название термина;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Идент. компонента.</b> Уникальный идентификатор компонента веб-приложения;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Тип компонента.</b> Тип компонента веб‑приложения, к которому привязывается термин, выбирается из списка: модуль, расширение модуля, виджет, плагин.</li>
    </ul>
</article>